python overlap.py \
    --data_list ../datasets/flores200_dataset/dev/cym_Latn.dev ../datasets/flores200_dataset/dev/dan_Latn.dev ../datasets/flores200_dataset/dev/eng_Latn.dev ../datasets/flores200_dataset/dev/spa_Latn.dev ../datasets/flores200_dataset/dev/fra_Latn.dev ../datasets/flores200_dataset/dev/gla_Latn.dev ../datasets/flores200_dataset/dev/hin_Deva.dev ../datasets/flores200_dataset/dev/ita_Latn.dev ../datasets/flores200_dataset/dev/jpn_Jpan.dev ../datasets/flores200_dataset/dev/kor_Hang.dev ../datasets/flores200_dataset/dev/khk_Cyrl.dev ../datasets/flores200_dataset/dev/por_Latn.dev ../datasets/flores200_dataset/dev/swe_Latn.dev ../datasets/flores200_dataset/dev/swh_Latn.dev ../datasets/flores200_dataset/dev/tam_Taml.dev ../datasets/flores200_dataset/dev/tha_Thai.dev ../datasets/flores200_dataset/dev/tuk_Latn.dev ../datasets/flores200_dataset/dev/zho_Hans.dev ../datasets/flores200_dataset/dev/zul_Latn.dev \
    --languages cy da en es fr gd hi it ja ko mn pt sv sw ta th tk zh_CN zu \
    --model_name GPT-4o-Mini-2024-07-18 \
    --output_path ../results/tokenization_analysis/overlap/GPT-4o-Mini-2024-07-18
python overlap.py \
    --data_list ../datasets/flores200_dataset/dev/cym_Latn.dev ../datasets/flores200_dataset/dev/dan_Latn.dev ../datasets/flores200_dataset/dev/eng_Latn.dev ../datasets/flores200_dataset/dev/spa_Latn.dev ../datasets/flores200_dataset/dev/fra_Latn.dev ../datasets/flores200_dataset/dev/gla_Latn.dev ../datasets/flores200_dataset/dev/hin_Deva.dev ../datasets/flores200_dataset/dev/ita_Latn.dev ../datasets/flores200_dataset/dev/jpn_Jpan.dev ../datasets/flores200_dataset/dev/kor_Hang.dev ../datasets/flores200_dataset/dev/khk_Cyrl.dev ../datasets/flores200_dataset/dev/por_Latn.dev ../datasets/flores200_dataset/dev/swe_Latn.dev ../datasets/flores200_dataset/dev/swh_Latn.dev ../datasets/flores200_dataset/dev/tam_Taml.dev ../datasets/flores200_dataset/dev/tha_Thai.dev ../datasets/flores200_dataset/dev/tuk_Latn.dev ../datasets/flores200_dataset/dev/zho_Hans.dev ../datasets/flores200_dataset/dev/zul_Latn.dev \
    --languages cy da en es fr gd hi it ja ko mn pt sv sw ta th tk zh_CN zu \
    --model_name Aya-Expanse-8B \
    --output_path ../results/tokenization_analysis/overlap/Aya-Expanse-8B
python overlap.py \
    --data_list ../datasets/flores200_dataset/dev/cym_Latn.dev ../datasets/flores200_dataset/dev/dan_Latn.dev ../datasets/flores200_dataset/dev/eng_Latn.dev ../datasets/flores200_dataset/dev/spa_Latn.dev ../datasets/flores200_dataset/dev/fra_Latn.dev ../datasets/flores200_dataset/dev/gla_Latn.dev ../datasets/flores200_dataset/dev/hin_Deva.dev ../datasets/flores200_dataset/dev/ita_Latn.dev ../datasets/flores200_dataset/dev/jpn_Jpan.dev ../datasets/flores200_dataset/dev/kor_Hang.dev ../datasets/flores200_dataset/dev/khk_Cyrl.dev ../datasets/flores200_dataset/dev/por_Latn.dev ../datasets/flores200_dataset/dev/swe_Latn.dev ../datasets/flores200_dataset/dev/swh_Latn.dev ../datasets/flores200_dataset/dev/tam_Taml.dev ../datasets/flores200_dataset/dev/tha_Thai.dev ../datasets/flores200_dataset/dev/tuk_Latn.dev ../datasets/flores200_dataset/dev/zho_Hans.dev ../datasets/flores200_dataset/dev/zul_Latn.dev \
    --languages cy da en es fr gd hi it ja ko mn pt sv sw ta th tk zh_CN zu \
    --model_name Llama-3.1-8B-Instruct \
    --output_path ../results/tokenization_analysis/overlap/Llama-3.1-8B-Instruct
python overlap.py \
    --data_list ../datasets/flores200_dataset/dev/cym_Latn.dev ../datasets/flores200_dataset/dev/dan_Latn.dev ../datasets/flores200_dataset/dev/eng_Latn.dev ../datasets/flores200_dataset/dev/spa_Latn.dev ../datasets/flores200_dataset/dev/fra_Latn.dev ../datasets/flores200_dataset/dev/gla_Latn.dev ../datasets/flores200_dataset/dev/hin_Deva.dev ../datasets/flores200_dataset/dev/ita_Latn.dev ../datasets/flores200_dataset/dev/jpn_Jpan.dev ../datasets/flores200_dataset/dev/kor_Hang.dev ../datasets/flores200_dataset/dev/khk_Cyrl.dev ../datasets/flores200_dataset/dev/por_Latn.dev ../datasets/flores200_dataset/dev/swe_Latn.dev ../datasets/flores200_dataset/dev/swh_Latn.dev ../datasets/flores200_dataset/dev/tam_Taml.dev ../datasets/flores200_dataset/dev/tha_Thai.dev ../datasets/flores200_dataset/dev/tuk_Latn.dev ../datasets/flores200_dataset/dev/zho_Hans.dev ../datasets/flores200_dataset/dev/zul_Latn.dev \
    --languages cy da en es fr gd hi it ja ko mn pt sv sw ta th tk zh_CN zu \
    --model_name Qwen3-8B \
    --output_path ../results/tokenization_analysis/overlap/Qwen3-8B